spring:
  profiles:
    active: diy
  rabbitmq:
    host: 10.250.7.21
    port: 30730
    username: guest
    password: guest
  main:
    web-application-type: none

management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
#      exposure:
#        include: "*"